### 查询服务
GET http://127.0.0.1:9001/knit/knit-cloud-nacos-client/nacos-client/service-instance?serviceId=knit-cloud-gateway
Accept: application/json
knit-cloud-user: eyJhbGciOiJSUzI1NiJ9.eyJrbml0LWNsb3VkLXVzZXIiOiJ7XCJpZFwiOjEwLFwidXNlcm5hbWVcIjpcIkltb29jUWlueWlJbW9vY0BpbW9vYy5jb21cIn0iLCJqdGkiOiJlN2MzNjdmNy00ZTcwLTRlZTQtYWU5NC1mMTQ3NmFhZjhhZGQiLCJleHAiOjE2NTY1MTg0MDB9.L6vvlB1-T-Tpss6OI1tSvQRpXF0fTTDUaWdv2aVfX-dwQ8idV3RUmSq5osBcVPcV6Bkv42qalxvjQr4QVrlG0U9HUzwfFBhVEXEDImzM_JyxteZ4rYS-Dgwofc2eBG6auRDeGrvx36LFKtYNoP-CgKjs1nHdz8JRMhbhggiIDRjLhnw38waRnHQTEyw80KDDXnkGx876umto8w6CpKfVr7DSBwoMfXBgeWMt6MynKT2YlvpCEIDb9HE8kly_MhGxfJOTWZ5mtMkIv6PMuvgSocuMhVLM085v59fsnMfWWBmMS-bKfwL8aMYHEEKA4XsQkgaU_QTPKzE-EVrizoeZ3g
token: knit
